/*
 * The PostHog project a game build sends its analytics to: its key, and its host, PostHog's EU cloud when
 * none is named. Each is the Gradle property `kvizic.posthog.key` or `kvizic.posthog.host`
 * (`-Pkvizic.posthog.key=...`, or `~/.gradle/gradle.properties`), or else the same name in the
 * repository's `local.properties`, which git ignores. No key is analytics off, which is how every test and
 * every CI build runs; a key is never committed, so a build made from the public repository never sends
 * to the developer's project.
 *
 * Applied by each module that builds an app from them, which reads what it needs:
 *
 * - `:app:androidApp` reads `extra["kvizicPosthogKey"]` and `extra["kvizicPosthogHost"]` into its
 *   BuildConfig, one key for every flavor (every event names its environment).
 * - `:app:webApp` sets `extra["kvizicAnalyticsPackage"]` first, and applies
 *   gradle/kvizic-version.gradle.kts, which sets `extra["kvizicAppVersion"]` and
 *   `extra["kvizicBuildNumber"]`; this then registers `generateKvizicAnalytics`, which writes the two
 *   settings, the version and the build number into Kotlin constants in that package, `POSTHOG_KEY`,
 *   `POSTHOG_HOST`, `APP_VERSION` and `BUILD_NUMBER`, whose output directory the module adds to its
 *   `webMain` sources. The build number is no analytics setting, but it is the version's, which is
 *   written here already.
 *
 * Desktop and iOS name theirs when the app starts: the `KVIZIC_POSTHOG_KEY` and `KVIZIC_POSTHOG_HOST`
 * variables, and the same build settings in the Xcode project's `Local.xcconfig`. A key holding anything
 * but letters, digits, `_` and `-`, or a host holding a quote, a backslash, a `$` or a space, fails the
 * build here, since each is written into generated code.
 */
import java.io.StringReader
import java.util.Properties

val localProperties =
    Properties().apply {
        providers
            .fileContents(rootProject.layout.projectDirectory.file("local.properties"))
            .asText
            .orNull
            ?.let { text -> load(StringReader(text)) }
    }

fun analyticsSetting(name: String): String =
    (providers.gradleProperty(name).orNull ?: localProperties.getProperty(name)).orEmpty().trim()

val posthogKey = analyticsSetting("kvizic.posthog.key")
val posthogHost = analyticsSetting("kvizic.posthog.host")

require(posthogKey.all { it.isLetterOrDigit() || it == '_' || it == '-' }) {
    "kvizic.posthog.key must be letters, digits, _ and -"
}
require(posthogHost.none { it == '"' || it == '\\' || it == '$' || it.isWhitespace() }) {
    "kvizic.posthog.host is no host: \"$posthogHost\""
}

extra["kvizicPosthogKey"] = posthogKey
extra["kvizicPosthogHost"] = posthogHost

if (extra.has("kvizicAnalyticsPackage")) {
    tasks.register("generateKvizicAnalytics") {
        // Read here, into locals, so the task action captures only these and not the script.
        val packageName = project.extra["kvizicAnalyticsPackage"] as String
        val appVersion = project.extra["kvizicAppVersion"] as String
        val buildNumber = project.extra["kvizicBuildNumber"] as Int
        val key = posthogKey
        val host = posthogHost
        val outputDir = layout.buildDirectory.dir("generated/kvizicAnalytics/kotlin")
        inputs.property("package", packageName)
        inputs.property("appVersion", appVersion)
        inputs.property("buildNumber", buildNumber)
        inputs.property("key", key)
        inputs.property("host", host)
        outputs.dir(outputDir)

        doLast {
            // Emptied first, so a file written into another package before cannot linger beside it.
            outputDir.get().asFile.deleteRecursively()
            val file = outputDir.get().file("${packageName.replace('.', '/')}/KvizicAnalytics.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                |package $packageName
                |
                |// Generated by generateKvizicAnalytics (gradle/kvizic-analytics.gradle.kts) from kvizic.posthog.key
                |// and kvizic.posthog.host. Do not edit, and never commit: the key is the developer's PostHog project's.
                |internal const val POSTHOG_KEY: String = "$key"
                |internal const val POSTHOG_HOST: String = "$host"
                |internal const val APP_VERSION: String = "$appVersion"
                |internal const val BUILD_NUMBER: Int = $buildNumber
                |
                """.trimMargin(),
            )
        }
    }
}
