/*
 * The server environment a browser build targets, from `-Pkvizic.env=dev`: local, dev or prod, local when
 * absent. A page has nothing of its own to read at start, so the name is written into a Kotlin constant,
 * `internal const val KVIZIC_ENV`, which the page's entry point parses.
 *
 * Applied by each module with a browser entry point, after it sets `extra["kvizicEnvPackage"]` to the
 * package the constant goes in:
 *
 *     extra["kvizicEnvPackage"] = "io.ntole.kvizic"
 *     apply(from = rootProject.file("gradle/kvizic-env.gradle.kts"))
 *
 * It registers `generateKvizicEnv`, whose output directory the module adds to its `webMain` sources. A
 * script rather than a plugin: it is one task, and a convention plugin would need an included build.
 *
 * Checked here as `KvizicEnvironment.parse` would, so a name it does not know fails the build rather
 * than every page load.
 */
tasks.register("generateKvizicEnv") {
    // Read here, into locals, so the task action captures only these and not the script.
    val packageName = project.extra["kvizicEnvPackage"] as String
    val requested = providers.gradleProperty("kvizic.env").orElse("")
    val outputDir = layout.buildDirectory.dir("generated/kvizicEnv/kotlin")
    inputs.property("package", packageName)
    inputs.property("environment", requested)
    outputs.dir(outputDir)

    doLast {
        val name =
            requested
                .get()
                .trim()
                .lowercase()
                .ifEmpty { "local" }
        require(name in setOf("local", "dev", "prod")) {
            "kvizic.env must be local, dev or prod, but is \"${requested.get()}\""
        }
        // Emptied first, so a constant written into another package before cannot linger beside it.
        outputDir.get().asFile.deleteRecursively()
        val file = outputDir.get().file("${packageName.replace('.', '/')}/KvizicEnv.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package $packageName
            |
            |// Generated by generateKvizicEnv (gradle/kvizic-env.gradle.kts) from -Pkvizic.env. Do not edit.
            |internal const val KVIZIC_ENV: String = "$name"
            |
            """.trimMargin(),
        )
    }
}
